name: PR Check
on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: yarn install

      - name: Run Lint
        run: yarn lint
